# Can't `COPY ..\ .` (up a directory) so either build outside the container or put all Dockerfiles in root

# FRAGILE: copy in entire solution, restore, (cache it), then throw most of it away

FROM microsoft/aspnetcore-build:2.0
WORKDIR /app

# cache restored packages as separate layer
COPY Shared/Shared.csproj Shared/Shared.csproj
COPY UserApi/UserApi.csproj UserApi/UserApi.csproj
COPY UserApi.Tests/UserApi.Tests.csproj UserApi.Tests/UserApi.Tests.csproj
COPY Web/Web.csproj Web/Web.csproj
COPY Web.Core/Web.Core.csproj Web.Core/Web.Core.csproj
COPY Web.Core.Tests/Web.Core.Tests.csproj Web.Core.Tests/Web.Core.Tests.csproj
COPY Fabricam.sln Fabricam.sln
RUN dotnet restore

COPY . .

WORKDIR /app/UserApi.Tests

RUN dotnet build

CMD ["dotnet", "test"]
